#!/usr/bin/env python3
"""Write PAPER_QUEUE.md: the order in which paper pages are built.

Order agreed with Bruno (9 Oct 2026):
  1. the 10 most-cited journal articles
  2. then journal articles where Bruno is first author
  3. then all remaining journal articles, newest to oldest
Only journal articles get full pages; conference papers and book chapters stay as list entries.

Citation counts come from Crossref (cached in data/citations.json; refresh with --refresh).
Crossref counts are lower than Google Scholar's but rank papers similarly.
Status comes from papers/data/<slug>.yml (draft or locked).
"""
from __future__ import annotations

import json
import sys
import time
import urllib.request
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
PUBS = ROOT / "data" / "publications.json"
CACHE = ROOT / "data" / "citations.json"
OUT = ROOT / "PAPER_QUEUE.md"
TOP_N = 10


def crossref_count(doi: str):
    req = urllib.request.Request(f"https://api.crossref.org/works/{doi}",
                                 headers={"User-Agent": "schivinski.github.io site builder"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)["message"].get("is-referenced-by-count")


def main() -> int:
    refresh = "--refresh" in sys.argv
    pubs = [p for p in json.loads(PUBS.read_text()) if p["type"] == "journal-article"]
    cache = json.loads(CACHE.read_text()) if CACHE.exists() else {}
    for p in pubs:
        doi = (p.get("doi") or "").lower()
        if doi and (refresh or doi not in cache):
            try:
                cache[doi] = crossref_count(doi)
                time.sleep(0.15)
            except Exception:
                cache.setdefault(doi, None)
    CACHE.write_text(json.dumps(cache, indent=1, sort_keys=True))

    status = {}
    for f in (ROOT / "papers" / "data").glob("*.yml"):
        d = yaml.safe_load(f.read_text())
        status[d["doi"].lower()] = (d.get("status", "draft"), f.stem)

    sys.path.insert(0, str(Path(__file__).parent))
    import fetch_publications as fp
    pubs = fp.with_extras(pubs)
    gs = {k.lower(): v for k, v in (fp.scholar_snapshot().get("papers") or {}).items()}

    def cites(p):
        k = fp.pub_key(p)
        return gs[k] if k in gs else cache.get((p.get("doi") or "").lower())

    fp.PAGES.update({d: "x" for d in status})
    top = fp.top_papers(pubs, {d: c for d, c in cache.items() if c is not None}, TOP_N)
    tier1 = top
    fp.HIGHLIGHTED_NOW.clear()
    tier2 = [c["p"] for c in fp.pick_highlights(pubs, top, cache)]
    used = {id(p) for p in tier1} | {id(p) for p in tier2}
    tier3 = sorted([p for p in pubs if id(p) not in used], key=lambda p: (-(p["year"] or 0), p["title"].lower()))

    lines = [
        "# Paper page queue",
        "",
        "Generated by `scripts/build_queue.py`. Order: the 10 most-cited MARKETING journal articles (the home-page top 10),",
        "then the highlighted papers (pinned + the ones the h-index booster picks), then the remaining articles from",
        "newest to oldest. Citation counts are from Google Scholar (data/scholar.yml snapshot) where available,",
        "otherwise Crossref. Only journal articles get full pages.",
        "",
    ]
    n = 0
    for label, group in [("Top 10 marketing papers", tier1), ("Highlighted papers", tier2), ("Newest to oldest", tier3)]:
        lines += [f"## {label} ({len(group)})", "", "| # | Year | Paper | Journal | Cited | Status |", "|---|---|---|---|---|---|"]
        for p in group:
            n += 1
            st = status.get((p.get("doi") or "").lower())
            st_txt = f"{st[0]} (`{st[1]}`)" if st else ""
            c = cites(p)
            title = p["title"].replace("|", "/")
            if len(title) > 90:
                title = title[:87] + "…"
            lines.append(f"| {n} | {p['year'] or ''} | {title} | {p['venue'] or ''} | {'' if c is None else c} | {st_txt} |")
        lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"Queue: {n} journal articles ({len(tier1)} / {len(tier2)} / {len(tier3)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
