#!/usr/bin/env python3
"""Write PAPER_QUEUE.md: the order in which paper pages are built.

Order agreed with Bruno (9 Oct 2026):
  1. the 10 most-cited journal articles
  2. then journal articles where Bruno is first author
  3. then all remaining journal articles, newest to oldest
Only journal articles get full pages; conference papers and book chapters stay as list entries.

Citation counts come from Crossref (cached in data/citations.json; refresh with --refresh).
Crossref counts are lower than Google Scholar's but rank papers similarly.
Status comes from papers/data/<slug>.yml (draft or locked).
"""
from __future__ import annotations

import json
import sys
import time
import urllib.request
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
PUBS = ROOT / "data" / "publications.json"
CACHE = ROOT / "data" / "citations.json"
OUT = ROOT / "PAPER_QUEUE.md"
TOP_N = 10


def crossref_count(doi: str):
    req = urllib.request.Request(f"https://api.crossref.org/works/{doi}",
                                 headers={"User-Agent": "schivinski.github.io site builder"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)["message"].get("is-referenced-by-count")


def main() -> int:
    refresh = "--refresh" in sys.argv
    pubs = [p for p in json.loads(PUBS.read_text()) if p["type"] == "journal-article"]
    cache = json.loads(CACHE.read_text()) if CACHE.exists() else {}
    for p in pubs:
        doi = (p.get("doi") or "").lower()
        if doi and (refresh or doi not in cache):
            try:
                cache[doi] = crossref_count(doi)
                time.sleep(0.15)
            except Exception:
                cache.setdefault(doi, None)
    CACHE.write_text(json.dumps(cache, indent=1, sort_keys=True))

    status = {}
    for f in (ROOT / "papers" / "data").glob("*.yml"):
        d = yaml.safe_load(f.read_text())
        status[d["doi"].lower()] = (d.get("status", "draft"), f.stem)

    def cites(p):
        return cache.get((p.get("doi") or "").lower())

    def first(p):
        return bool(p["authors"]) and "schivinski" in p["authors"][0].lower()

    with_counts = sorted([p for p in pubs if cites(p) is not None], key=lambda p: -cites(p))
    tier1 = with_counts[:TOP_N]
    used = {id(p) for p in tier1}
    tier2 = sorted([p for p in pubs if id(p) not in used and first(p)],
                   key=lambda p: (-(p["year"] or 0), p["title"].lower()))
    used |= {id(p) for p in tier2}
    tier3 = sorted([p for p in pubs if id(p) not in used], key=lambda p: (-(p["year"] or 0), p["title"].lower()))

    lines = [
        "# Paper page queue",
        "",
        "Generated by `scripts/build_queue.py`. Order: the 10 most-cited journal articles, then articles with",
        "Bruno as first author, then the remaining articles from newest to oldest. Citation counts are from",
        "Crossref and run lower than Google Scholar's. Only journal articles get full pages.",
        "",
    ]
    n = 0
    for label, group in [("Most cited", tier1), ("First author", tier2), ("Newest to oldest", tier3)]:
        lines += [f"## {label} ({len(group)})", "", "| # | Year | Paper | Journal | Cited | Status |", "|---|---|---|---|---|---|"]
        for p in group:
            n += 1
            st = status.get((p.get("doi") or "").lower())
            st_txt = f"{st[0]} (`{st[1]}`)" if st else ""
            c = cites(p)
            title = p["title"].replace("|", "/")
            if len(title) > 90:
                title = title[:87] + "…"
            lines.append(f"| {n} | {p['year'] or ''} | {title} | {p['venue'] or ''} | {'' if c is None else c} | {st_txt} |")
        lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"Queue: {n} journal articles ({len(tier1)} / {len(tier2)} / {len(tier3)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
